version: "3.0"
services:
  healthcheck:
    image: kukuhsatrio/cicdhealthcheck:development
    container_name: healthcheck
    ports:
      - 4000:4000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
        - "80:80"