name: Deploy With Semantic Tag Release

on:
  push:
    branches:
      - main

permissions:
  contents: write      

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Set environment variables
        env:
            ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
            echo $ENV_FILE | base64 --decode >> /home/runner/work/cicd-healthcheck/cicd-healthcheck/.env
            ls -l
          
      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint        

      - name: Run Testing
        run: npm run test -- --exit        

      - name: git config
        run: |
          git config user.name "ksatriow"
          git config user.email "andkukuh@gmail.com"
      - run: npm run releaseci
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}      

      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
            rename: '@jaywcjlove/github-action-package-test'
        
      - run: echo "version - ${{ steps.info.outputs.version }}"
        
  ggshield-secret-scan-main:
    name: ggshield secret scan, using the action from ggshield repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan Secret
        uses: GitGuardian/ggshield/actions/secret@main
        with:
          args: -v --all-policies
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
  
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'sarif'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL'
  
      - name: Run Checkov
        run: |
             docker run -t -v ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov --directory . --skip-check CKV2_GHA_1

    #   -
    #     name: Set up QEMU
    #     uses: docker/setup-qemu-action@v2
    #   -
    #     name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2          
    
          
    #   - name: Login to DockerHub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Build and push
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: .
    #       push: true
    #       tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }}
    #       file: /home/komar/actions-runner/_work/cicd/cicd/Dockerfile

