name: Deploy With Semantic Tag Release

on:
  push:
    branches:
      - main

permissions:
  contents: write      

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Set environment variables
        env:
            ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
            echo $ENV_FILE | base64 --decode >> /home/runner/work/cicd-healthcheck/cicd-healthcheck/.env
            ls -l
          
      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint        

      - name: Run Testing
        run: npm run test -- --exit        

      - name: git config
        run: |
          git config user.name "ksatriow"
          git config user.email "andkukuh@gmail.com"
      - run: npm run releaseci
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}      

      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
            rename: '@jaywcjlove/github-action-package-test'
        
      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"
        

    #   - name: Semantic versioning
    #     id: versioning
    #     uses: PaulHatch/semantic-version@v4.0.2
    #     with:
    #       branch: main
    #       tag_prefix: "v"
    #       major_pattern: "BREAKING CHANGE:"
    #       minor_pattern: "feat:"
    #       format: "v${major}.${minor}.${patch}-prerelease${increment}"
          
    #   -
    #     # Add support for more platforms with QEMU (optional)
    #     # https://github.com/docker/setup-qemu-action
    #     name: Set up QEMU
    #     uses: docker/setup-qemu-action@v2
    #   -
    #     name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2          
    
          
    #   - name: Login to DockerHub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Build and push
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: .
    #       push: true
    #       tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }}
    #       file: /home/komar/actions-runner/_work/cicd/cicd/Dockerfile

